[package]
name = "wg-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
awc = "3.2"
ed25519-dalek = "2"
env_logger = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = "1.23.1"
